server:
  port: 7071
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kevinraf/ACAD-ACIBER.git # ruta del repositorio git
          searchPaths: config-data
          default-label: master
  security:
    user:
      name: root
      password: alan